In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7])  #using list 

In [6]:
type(a)

numpy.ndarray

In [5]:
b = np.array((1,2,3,4,5,6,7))   #using tuple

In [7]:
type(b)

numpy.ndarray

In [24]:
l = [22,33,44,55,66,77]        #list to arraylist

In [26]:
l1 = np.array(l)
l1

array([22, 33, 44, 55, 66, 77])

create a 1D numpy array containing first 12 positive intergers as arr1

In [46]:
arr1 = np.arange(1,13)   #method 1
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
arr1 = np.array(range(1,13))   #method 2
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## create a 1D numpy array1 with 20 elements containing intergers between 0 to 12 using linspace.

In [28]:
array1 = np.linspace(0,12,20)

In [29]:
array1

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

attributes of array1

In [34]:
array1.dtype

dtype('float64')

In [35]:
array1.ndim

1

In [37]:
array1.nbytes

160

In [38]:
array1.size

20

In [39]:
array1.itemsize

8

In [40]:
array1

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

## attributes of array2

In [49]:
array2 = np.arange(1,13)
array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
array2.ndim

1

In [53]:
array2.dtype

dtype('int32')

In [57]:
array2.nbytes

48

In [58]:
array2.size

12

In [59]:
array2.itemsize

4

## measure of central tendency 

In [90]:
array1

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

In [91]:
np.mean(array1)

5.999999999999999

In [92]:
np.median(array1)

6.0

## measure of spread of array1

##### range()

In [98]:
range1 = max(array1) - min(array1)
range1

12.0

##### IQR

In [99]:
q3 = np.percentile(array1,75)
q1 = np.percentile(array1,25)

In [100]:
IQR = q3 - q1
IQR

6.0

##### variance

In [101]:
np.var(array1)

13.26315789473684

##### standard deviation

In [102]:
np.std(array1)

3.6418618720013036

##### outliers of array1

In [106]:
lower1 = q1 -(1.5*IQR)
lower1

-6.0

In [107]:
upper1 = q3 +(1.5*IQR)
upper1

18.0

In [109]:
array1

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

In [112]:
array1<lower1   #no outliers

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [111]:
array1>upper1   #no outliers

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

## measure of central tendency of array2


In [93]:
array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [95]:
np.mean(array2)

6.5

In [96]:
np.median(array2)

6.5

## Measure of spread of array2

##### range of array2

In [115]:
range2 = max(array2) - min(array2)
range2

11

##### IQR

In [113]:
Q3 = np.percentile(array2,75)
Q1 = np.percentile(array2,25)

In [118]:
IQR1 = Q3-Q1
IQR1

5.5

##### standard deviation

In [117]:
np.std(array2)
array1

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

##### variance

In [75]:
np.var(array2)

11.916666666666666

##### outliers of array2

In [119]:
lower2 = Q1 -(1.5*IQR1)
lower2

-4.5

In [120]:
upper2 = Q3 +(1.5*IQR1)
upper2

17.5

In [127]:
array2<lower2      #no outliers

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [126]:
array2>upper2   #no outliers

array([False, False, False, False, False, False, False, False, False,
       False, False, False])