**Creation of ndarray**

1. Write python code to create 3d array in different ways with 15 elements.
2. Array Creation:
a. Create a 4D NumPy array containing the first 12 positive integers as arr1.
b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.
3. Find all attributes of array1 and array2
4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.


**Array Slicing and Indexing:**

a. Creating Arrays:
      - Create a 1-dimensional NumPy array  arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
      - Create a 2-dimensional NumPy array  arr2  with the values  [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
      
 b.Basic Indexing:
      - Print the element at index 3 of  arr1.
      - Print the element at row 2, column 1 of  arr2

   c. Array Slicing:
      - Print the first five elements of `arr1`.
      - Print the subarray of `arr2` consisting of the last two rows and the first two columns.
       - Print every second element starting from index 1 up to index 7 of `arr1`.







**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
      - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
      - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.
      
b. Data Type Conversion:
      - Convert the `float_array` to an array with data type `int32`. Print the result.
      - Convert the `int_array` to an array with data type `float32`. Print the result.

**Generating Random Numbers:**

1.	Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2.	Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3.	Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4.	Apply descriptive statistics for rand_matrix.


**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:
1.	How many employees are getting more less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?



Write python code to create 3d array in different ways with 15 elements.

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15], ndmin = 3)

In [5]:
a.ndim

3

In [6]:
a = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]])

In [7]:
a.ndim

3

In [8]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]).reshape(1,5,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]])

In [9]:
import random

In [10]:
a = np.arange(1,16).reshape(1,5,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]])

Array Creation: a. Create a 4D NumPy array containing the first 12 positive integers as arr1.

In [11]:
arr1 = np.arange(1,13)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.

In [12]:
import random

In [14]:
array1 = np.random.rand(20).reshape(1,4,5)
array1

array([[[0.68612717, 0.09339592, 0.85088755, 0.26851174, 0.98918982],
        [0.50824608, 0.8648666 , 0.96048357, 0.80002711, 0.73712403],
        [0.76668921, 0.43000506, 0.8675711 , 0.24384842, 0.53347692],
        [0.58295416, 0.81735869, 0.55757414, 0.31469898, 0.14308958]]])

Find all attributes of array1 and array2


In [16]:
array1.dtype

dtype('float64')

In [17]:
array1.nbytes

160

In [18]:
array1.size

20

In [21]:
array1.itemsize

8

In [22]:
arr1.dtype

dtype('int32')

In [23]:
arr1.nbytes

48

In [24]:
arr1.itemsize

4

In [25]:
arr1.size

12

Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

##### descriptive statistic on arr1

In [26]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
arr1.mean()

6.5

In [30]:
np.median(arr1)

6.5

In [31]:
np.var(arr1)

11.916666666666666

In [32]:
np.std(arr1)

3.452052529534663

In [39]:
a = np.min(arr1)

In [38]:
b = np.max(arr1)

In [40]:
ra = b - a   #range 

11

In [41]:
q1 = np.percentile(arr1,25)

In [42]:
q3 = np.percentile(arr1,75)

In [43]:
IQR = q3- q1

In [45]:
lower = q1-(1.5*IQR)
upper = q3+(1.5*IQR)

In [47]:
arr1[arr1<lower]

array([], dtype=int32)

In [48]:
arr1[arr1>upper]

array([], dtype=int32)

##### descriptive statistics on array1

In [49]:
array1

array([[[0.68612717, 0.09339592, 0.85088755, 0.26851174, 0.98918982],
        [0.50824608, 0.8648666 , 0.96048357, 0.80002711, 0.73712403],
        [0.76668921, 0.43000506, 0.8675711 , 0.24384842, 0.53347692],
        [0.58295416, 0.81735869, 0.55757414, 0.31469898, 0.14308958]]])

In [50]:
array1.mean()

0.600806291275301

In [51]:
np.median(array1)

0.6345406629314067

In [54]:
a1 = np.max(array1)
b1 = np.min(array1)

In [56]:
r1 = a1-b1
r1           #range of array1

0.8957939012622964

In [57]:
np.std(array1)

0.26969723185477756

In [58]:
np.var(array1)

0.07273659687012965

In [60]:
q1 = np.percentile(array1,25)
q3 = np.percentile(array1,75)

In [61]:
iqr = q3-q1
iqr

0.42456236893815524

In [65]:
lower1 = q1-(1.5*iqr)
upper1 = q3+(1.5*iqr)

In [67]:
array1[array1<lower1]

array([], dtype=float64)

In [69]:
array1[array1>upper1]

array([], dtype=float64)

Array Slicing and Indexing:

a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. - Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].


In [89]:
arr1 = np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])

In [90]:
arr2 =np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

b.Basic Indexing: - Print the element at index 3 of arr1. - Print the element at row 2, column 1 of arr2



In [75]:
arr1[3]

73

In [76]:
arr2[1][0]

3

c. Array Slicing: - Print the first five elements of arr1. - Print the subarray of arr2 consisting of the last two rows and the first two columns. - Print every second element starting from index 1 up to index 7 of arr1.

In [77]:
arr1[0:5]

array([ 0, 11, 26, 73, 42])

In [78]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
arr2[1:3,0:2]

array([[3, 4],
       [6, 7]])

In [80]:
arr1[1:8]

array([11, 26, 73, 42, 51,  6, 77])

a. Creating Arrays with Specific Data Types: - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. - Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.


In [81]:
int_array = np.array([1, 2, 3, 4, 5], dtype = 'int16')

In [82]:
int_array.dtype

dtype('int16')

In [83]:
float_array = np.array([0.1, 0.2, 0.3, 0.4, 0.5], dtype = 'float64')

In [84]:
float_array.dtype

dtype('float64')

b. Data Type Conversion: - Convert the float_array to an array with data type int32. Print the result. - Convert the int_array to an array with data type float32. Print the result.

In [73]:
float_int = float_array.astype(np.int32)

In [74]:
float_int.dtype

dtype('int32')

In [75]:
int_float = int_array.astype(np.float32)

In [76]:
int_float

array([1., 2., 3., 4., 5.], dtype=float32)

Generating Random Numbers:

Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).


In [80]:
import random

In [88]:
rand_integers = np.random.randint(0,100,10)
rand_integers

array([62, 11, 34,  8, 97, 11, 63, 56, 41, 16])

Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.


In [87]:
rand_uniform = np.random.uniform(-1,1,5)
rand_uniform

array([ 0.49854977, -0.38045989,  0.31664605,  0.61406167, -0.90072602])

Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix


In [86]:
rand_matrix = np.random.randint(50,101,16).reshape(4,4)
rand_matrix

array([[92, 59, 81, 98],
       [99, 73, 55, 80],
       [93, 72, 86, 89],
       [76, 91, 87, 79]])

Apply descriptive statistics for rand_matrix.

In [91]:
rand_matrix.mean()

81.875

In [94]:
np.median(rand_matrix)

83.5

In [95]:
np.var(rand_matrix)

151.609375

In [96]:
np.std(rand_matrix)

12.312975879128489

In [98]:
q1 = np.percentile(rand_matrix,25)
q3 = np.percentile(rand_matrix,75)

In [100]:
iqr = q3-q1
iqr

16.0

In [101]:
lower = 25-(1.5*iqr)
upper = 75+(1.5*iqr)

In [102]:
rand_matrix[rand_matrix<lower]

array([], dtype=int32)

In [103]:
rand_matrix[rand_matrix>upper]

array([], dtype=int32)

Analyze the Data:

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]



In [104]:
salaries = np.array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638])

Describe the data using numpy array. Measure the following: 1. How many employees are getting more less than 50000?



In [106]:
salaries[salaries<50000]

array([31250, 39828, 41671, 34225, 32199])

What is the median salary?


In [107]:
np.median(salaries)

61699.5

In [109]:
r = max(salaries) - min(salaries)
r   #range

3082388

In [111]:
np.var(salaries)

299951833234.73895

In [118]:
average = np.mean(salaries)

In [113]:
q1 = np.percentile(salaries,25)
q3 = np.percentile(salaries,75)
iqr = q3-q1
iqr

31533.25

In [121]:
salaries[(salaries > average) & (salaries >= q3)]

array([3113638])

In [120]:
salaries[salaries<q1]

array([52453, 31250, 39828, 41671, 51428, 50477, 34225, 32199])

In [113]:
q1 = np.percentile(salaries,25)
q3 = np.percentile(salaries,75)
iqr = q3-q1
iqr

31533.25

In [122]:
lower = q1-(1.5*iqr)
upper = q3+(1.5*iqr)

In [124]:
salaries[salaries>upper]

array([3113638])

In [125]:
salaries[salaries<lower]

array([], dtype=int32)