### Data Cleaning using numpy

**The following are the student marks of a class**
[44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]



In [1]:
import numpy as np

In [2]:
marks = np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53,44])

1. Find the no of outliers and missing values?
2. replace the outliers with 45 and missing value with 87.
3. what is the average marks of students after 2nd step?
4. How many students got less than 60 marks?
5. what is the maximum marks?
6. Convert the marks to float32.

In [3]:
#outliers

In [4]:
marks[marks>100]

array([188., 120., 122.])

In [5]:
len(marks[marks>100])

3

In [6]:
#missing values

In [7]:
np.isnan(marks)  #'True' are the missing values

array([False, False,  True, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False])

In [8]:
sum(np.isnan(marks))  #these are the no. of missing values

4

2. replace the outliers with 45 and missing value with 87.

In [9]:
marks = np.where(np.isnan(marks),87,marks).astype('float32')#missing values replaced with 87
marks

array([ 44.,  24.,  87.,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  87.,  87.,   3.,  56.,  81.,  59., 122.,  92.,  87.,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.], dtype=float32)

In [10]:
ou = marks>100
ou

array([False, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [11]:
np.sum(ou)

3

In [12]:
marks = np.where(ou,45,marks)  #outliers replaced with 45

In [13]:
marks

array([44., 24., 87., 59., 32., 96., 45., 52., 62., 58., 52., 45., 87.,
       87.,  3., 56., 81., 59., 45., 92., 87., 87., 96., 97.,  1., 19.,
        2., 53., 44.], dtype=float32)

what is the average marks of students after 2nd step?

In [14]:
ave = np.mean(marks)
ave

56.96552

How many students got less than 60 marks?

In [15]:
len(marks[marks<60])

18

what is the maximum marks?
Convert the marks to float32.

In [16]:
np.max(marks)

97.0

In [17]:
marks.dtype

dtype('float32')

### Solving Linear Equations


    
1. 2x + 3y - z = 10

    x - y + 2z = 5
    
    3x + 2y + z = 12
    
    
    
2. 2x + y - z + 3w = 8

    3x - 2y + 2z + 2w = 1
    
    x + 3y - 2z + w = 7
    
    4x - y + z - 2w = 3
   
   
   
3. 4x + 2y - 3z = 10

    -2x + 3y + z = -3
    
    x - y + 2z = 4
    
Solve the system of equations using NumPy's linalg.solve function.


In [22]:
a = np.array([[2,3,-1],[1,-1,2],[3,2,1]])
a

array([[ 2,  3, -1],
       [ 1, -1,  2],
       [ 3,  2,  1]])

In [23]:
b = np.array([10,5,12])
b

array([10,  5, 12])

In [24]:
np.linalg.solve(a,b)

array([-6.75539944e+15,  6.75539944e+15,  6.75539944e+15])

In [ ]:
2x + y - z + 3w = 8

3x - 2y + 2z + 2w = 1

x + 3y - 2z + w = 7

4x - y + z - 2w = 3

In [18]:
s = np.array([[2,1,-1,3], [3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])

In [19]:
s1 = np.array([8,1,7,3])

In [28]:
np.linalg.solve(s,s1)

array([ 1.73170732, -0.75609756, -3.46341463,  0.6097561 ])

In [ ]:
4x + 2y - 3z = 10

-2x + 3y + z = -3

x - y + 2z = 4

In [36]:
d = np.array([[4,2,-3],[-2,3,1],[1,-1,2]])

In [37]:
d1 = np.array([10,-3,4])

In [39]:
np.linalg.solve(d,d1)

array([2.85365854, 0.6097561 , 0.87804878])

### Conditional Selection with np.where()


1.	Generate a random 1D array A of 10 integers between 1 and 100.

2.	Use np.where() to find the indices where the elements of A are greater than 50.

3.	Create a new array B that contains elements from A where the condition is met.

4.	Calculate the mean of array B and print it along with arrays A and B.

In [47]:
A = np.arange(1,100)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [51]:
B = np.where((A>50))
B

(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98],
       dtype=int64),)

In [53]:
np.mean(B)

74.0

### Replace Values with np.where()

1.	Create a 4x4 random integer matrix C with values between -10 and 10.

2.	Use np.where() to replace all negative values in matrix C with 0.

3.	Print the original matrix C and the modified matrix.

In [58]:
C = np.random.randint(-10,10,16).reshape(4,4)
C

array([[-5, -5,  3,  9],
       [ 4, -1,  8, -6],
       [-8,  3, -8, -3],
       [-6,  7,  5, -6]])

In [62]:
C = np.where(C<0,0,C)
C

array([[0, 0, 3, 9],
       [4, 0, 8, 0],
       [0, 3, 0, 0],
       [0, 7, 5, 0]])